/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.tigrium.csomozottkarkoto.gui;

import hu.tigrium.csomozottkarkoto.data.Karkoto;
import hu.tigrium.csomozottkarkoto.data.Szal;
import java.awt.Color;

/**
 *
 * @author Kata
 */
public class Keret extends javax.swing.JFrame {
    private HaloPanel panel;
    /**
     * Creates new form Keret
     */
    public Keret(Karkoto karkoto) {
        initComponents();
//        Szal[] szalak = new Szal[]{new Szal("B", Color.red), new Szal("B", Color.red),
//                new Szal("F", Color.black), new Szal("S", Color.yellow), 
//                new Szal("S", Color.yellow), new Szal("F", Color.black)};
        Szal[] szalak = karkoto.getKezdoSzalak();
        panel = new HaloPanel(szalak, 20);
        panel.setKarkoto(karkoto);
        add(panel);
        pack();
    }

    public HaloPanel getPanel() {
        return panel;
    }

    public void setPanel(HaloPanel panel) {
        this.panel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
