/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.tigrium.csomozottkarkoto.gui;

import hu.tigrium.csomozottkarkoto.CsomozottKarkoto;
import hu.tigrium.csomozottkarkoto.data.Karkoto;
import hu.tigrium.csomozottkarkoto.data.Szal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.EventListener;
import java.util.List;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Kata
 */
public class SettingsPanel extends javax.swing.JPanel {
    private List<SzalSzin> szalszin;
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        szalszin = new ArrayList<SzalSzin>();
        SpinnerModel model = new SpinnerNumberModel(CsomozottKarkoto.getKarkoto().getSzalak().length, 4, 20, 1);
        szalakSzama.setModel(model);
        szinek();
        
//        szalakSzama.addChangeListener(new ChangeListener() {
//            @Override
//            public void stateChanged(ChangeEvent e) {
//                CsomozottKarkoto.setKarkoto(new Karkoto((int)szalakSzama.getValue()));
//                CsomozottKarkoto.getKeret().repaint();
//                szinek();
//            }
//        });
    }
    
    private void szinek() {
        for (SzalSzin sz : szalszin) {
            szinek.remove(sz);
        }
        
        szalszin.clear();
        
        for (int i = 0; i < getSzalakSzama(); i++) {
            szalszin.add(new SzalSzin(CsomozottKarkoto.getKarkoto().getSzal(i).getSzin(), i));
        }
        
        for (SzalSzin sz : szalszin) {
            szinek.add(sz);
        }
        
        validate();
        repaint();
    }

    private int getSzalakSzama() {
        return (int) szalakSzama.getValue();
    }
    
    protected void setSzalSzin() {
        for (int i = 0; i < szalszin.size();i++) {
            CsomozottKarkoto.getKarkoto().getSzalak()[i].setSzin(szalszin.get(i).getSzin());
        }
    }
    
    public void update() {
        szalakSzama.setValue(CsomozottKarkoto.getKarkoto().getSzalak().length);
        szinek();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        szalakSzama = new javax.swing.JSpinner();
        scroll = new javax.swing.JScrollPane();
        szinek = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kezdő szálak"));

        jLabel1.setText("Szálak száma:");

        jLabel2.setText("Szálak:");

        szalakSzama.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                szalakSzamaStateChanged(evt);
            }
        });

        scroll.setBorder(null);

        szinek.setLayout(new javax.swing.BoxLayout(szinek, javax.swing.BoxLayout.PAGE_AXIS));
        scroll.setViewportView(szinek);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(szalakSzama, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(szalakSzama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void szalakSzamaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_szalakSzamaStateChanged
        
    }//GEN-LAST:event_szalakSzamaStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSpinner szalakSzama;
    private javax.swing.JPanel szinek;
    // End of variables declaration//GEN-END:variables
}
