/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.tigrium.csomozottkarkoto.gui;

import java.awt.Color;

/**
 *
 * @author Kata
 */
public class SzalSzin extends javax.swing.JPanel {

    /**
     * Creates new form SzalSzin
     */
    public SzalSzin() {
        initComponents();
    }
    
    public SzalSzin(Color szin) {
        this();
        setSzin(szin);
    }
    
    public Color getSzin() {
        return szinminta.getBackground();
    }
    
    public void setSzin(Color szin) {
        szinminta.setBackground(szin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        szinminta = new javax.swing.JPanel();
        modosit = new javax.swing.JButton();

        javax.swing.GroupLayout szinmintaLayout = new javax.swing.GroupLayout(szinminta);
        szinminta.setLayout(szinmintaLayout);
        szinmintaLayout.setHorizontalGroup(
            szinmintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        szinmintaLayout.setVerticalGroup(
            szinmintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        modosit.setText("Módosít");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(szinminta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modosit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(szinminta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(modosit)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton modosit;
    private javax.swing.JPanel szinminta;
    // End of variables declaration//GEN-END:variables
}
